[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DUSER_SETUP_LOADED
    -DST7735_DRIVER
    -DST7735_BLACKTAB
    -DUSE_FSPI_PORT
    -DTFT_WIDTH=128
    -DTFT_HEIGHT=160
    -DTFT_MOSI=41
    -DTFT_SCLK=40
    -DTFT_CS=39
    -DTFT_DC=38
    -DTFT_RST=47
    -DTFT_BL=21
    -DSPI_FREQUENCY=27000000
    -DSPI_READ_FREQUENCY=5000000
    -DLOAD_GLCD
    -DLOAD_FONT2
    -DLOAD_FONT4
    -DLOAD_FONT6
    -DLOAD_FONT7
    -DLOAD_GFXFF
    -DSMOOTH_FONT
    -DTOUCH_CS=-1
    -I include
    -I .

lib_extra_dirs = ../shared

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43
