[env:nano]
platform = atmelavr
board = nanoatmega328
framework = arduino

monitor_speed = 115200

build_flags =
    -I include

lib_extra_dirs = ../share

lib_deps =
    mikem/RadioHead @ ^1.120
    paulstoffregen/OneWire @ ^2.3.7
    milesburton/DallasTemperature @ ^3.9.0
    teckel12/NewPing @ ^1.9.7
